#!/bin/sh
# Standardized tmux popup launcher with size presets.
# Usage: tmux-popup [-s SIZE] [-t TITLE] [-d DIR] [-w WIDTH] [-h HEIGHT] [-x XPOS] [-y YPOS] [-E] COMMAND [ARGS...]

set -e

SIZE="medium"
TITLE=""
DIR="#{pane_current_path}"
CUSTOM_WIDTH=""
CUSTOM_HEIGHT=""
XPOS=""
YPOS=""
EXIT_ON_CLOSE=""

while [ $# -gt 0 ]; do
  case "$1" in
    -s|--size)
      SIZE="$2"
      shift 2
      ;;
    -t|--title)
      TITLE="$2"
      shift 2
      ;;
    -d|--dir)
      DIR="$2"
      shift 2
      ;;
    -w|--width)
      CUSTOM_WIDTH="$2"
      shift 2
      ;;
    -h|--height)
      CUSTOM_HEIGHT="$2"
      shift 2
      ;;
    -x|--xpos)
      XPOS="$2"
      shift 2
      ;;
    -y|--ypos)
      YPOS="$2"
      shift 2
      ;;
    -E|--exit-on-close)
      EXIT_ON_CLOSE="-E"
      shift
      ;;
    -H|--help)
      cat <<'EOF'
Usage: tmux-popup [OPTIONS] COMMAND [ARGS...]

OPTIONS:
  -s, --size SIZE     Preset size: xsmall, small, medium, large, full
  -t, --title TITLE   Popup title
  -d, --dir DIR       Working directory
  -w, --width WIDTH   Custom width
  -h, --height HEIGHT Custom height
  -x, --xpos POS      Horizontal position
  -y, --ypos POS      Vertical position
  -E                  Close popup when command exits
EOF
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      break
      ;;
  esac
done

if [ $# -eq 0 ]; then
  echo "Error: No command specified" >&2
  exit 1
fi

case "$SIZE" in
  xsmall)
    PRESET_WIDTH="60%"
    PRESET_HEIGHT="20"
    ;;
  small)
    PRESET_WIDTH="80%"
    PRESET_HEIGHT="70%"
    ;;
  medium)
    TERM_WIDTH=$(tmux display-message -p '#{window_width}')
    TERM_HEIGHT=$(tmux display-message -p '#{window_height}')
    WIDTH_90=$((TERM_WIDTH * 90 / 100))
    HEIGHT_90=$((TERM_HEIGHT * 90 / 100))

    if [ "$WIDTH_90" -gt 250 ]; then
      PRESET_WIDTH="250"
    else
      PRESET_WIDTH="90%"
    fi

    if [ "$HEIGHT_90" -gt 100 ]; then
      PRESET_HEIGHT="100"
    else
      PRESET_HEIGHT="90%"
    fi
    ;;
  large)
    PRESET_WIDTH="90%"
    PRESET_HEIGHT="90%"
    ;;
  full)
    PRESET_WIDTH="100%"
    PRESET_HEIGHT="100%"
    ;;
  *)
    echo "Error: Invalid size preset: $SIZE" >&2
    exit 1
    ;;
esac

WIDTH="${CUSTOM_WIDTH:-$PRESET_WIDTH}"
HEIGHT="${CUSTOM_HEIGHT:-$PRESET_HEIGHT}"

TERM_WIDTH=${TERM_WIDTH:-$(tmux display-message -p '#{window_width}')}
TERM_HEIGHT=${TERM_HEIGHT:-$(tmux display-message -p '#{window_height}')}
MAX_WIDTH=$((TERM_WIDTH * 90 / 100))
MAX_HEIGHT=$((TERM_HEIGHT * 90 / 100))

case "$WIDTH" in
  *%) ;;
  *) [ "$WIDTH" -gt "$MAX_WIDTH" ] && WIDTH="$MAX_WIDTH" ;;
esac

case "$HEIGHT" in
  *%) ;;
  *) [ "$HEIGHT" -gt "$MAX_HEIGHT" ] && HEIGHT="$MAX_HEIGHT" ;;
esac

if [ -n "$EXIT_ON_CLOSE" ]; then
  set -- "-E" "$@"
fi

set -- "-w" "$WIDTH" "-h" "$HEIGHT" "$@"

if [ -n "$XPOS" ]; then
  set -- "-x" "$XPOS" "$@"
fi

if [ -n "$YPOS" ]; then
  set -- "-y" "$YPOS" "$@"
fi

set -- "-d" "$DIR" "$@"

if [ -n "$TITLE" ]; then
  set -- "-T" "$TITLE" "$@"
fi

set -- "-e" "TMUX_IN_POPUP=1" "$@"

exec tmux display-popup "$@"
