# Window Customisation
window:
  dimensions:
    columns: 120
    lines: 40
  padding:
    x: 30
    y: 30
  decorations: buttonless

scrolling:
  history: 10000
  multiplier: 3

background_opacity: 0.95

# Font configuration
font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic
  size: 13.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#262626'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

  cursor:
    style: Block
    unfocused_hollow: true
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: '0xffffff'
    background: '0xdc3232'
    white: '0xffffff'

  search:
    matches:
      foreground: '#000000'
      background: '#ffffff'

    bar:
      background: '#c5c8c6'
      foreground: '#1d1f21'

# Key bindings
key_bindings:
  - { key: N,        mods: Control|Shift,    action: SpawnNewInstance    }
