# Window Customisation
window:
  dimensions:
    columns: 120
    lines: 40
  padding:
    x: 30
    y: 30
  decorations: buttonless

scrolling:
  history: 10000
  multiplier: 3

background_opacity: 0.95

# Font configuration
font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  size: 14.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: "#222433"
    # soft contrast: background = '#32302f'
    foreground: "#9ea3c0"

  # Normal colors
  normal:
    black: "#111219"
    red: "#db5966"
    green: "#7cbe8c"
    yellow: "#9b956b"
    blue: "#2994c6"
    magenta: "#6c75cb"
    cyan: "#73c1a9"
    white: "#9ea3c0"

  # Bright colors
  bright:
    black: "#6A709C"
    red: "#FD6776"
    green: "#96E6A9"
    yellow: "#DFD69A"
    blue: "#35BFFF"
    magenta: "#8893FF"
    cyan: "#84DEC2"
    white: "#D0D7FD"

  cursor:
    style: Block
    unfocused_hollow: true
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: "0xffffff"
    background: "0xdc3232"
    white: "0xffffff"

  search:
    matches:
      foreground: "#000000"
      background: "#ffffff"

    bar:
      background: "#c5c8c6"
      foreground: "#1d1f21"

# Key bindings
key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
