[metadata]
name = "files"
description = "Select and open files"
requirements = ["fd", "bat"]

[source]
command = ["fd -t f", "fd -t f -H"]

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "Open the selected file in $EDITOR"
command = "${EDITOR:-vim} '{}'"
mode = "execute"
