# Window Customisation
window:
  dimensions:
    columns: 85
    lines: 25
  position:
    x: 310
    y: 500
  padding:
    x: 30
    y: 30
  decorations: buttonless

scrolling:
  history: 10000
  multiplier: 3

background_opacity: 1

# Font configuration
font:
  normal:
    family: FiraCode Nerd Font
    style: Light
  bold:
    family: FiraCode Nerd Font
    style: Medium
  italic:
    family: FiraCode Nerd Font
    style: Italic
  size: 14.0

  offset:
    x: 0
    y: 2

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

# Colors (Lunar)
# colors:
#   # Default colors
#   primary:
#     background: "#222732"
#     # background: "#2E3440"
#     foreground: "#AAB2C0"
# 
#   # Normal colors
#   normal:
#     black: "#3B4252"
#     red: "#CC5A68"
#     green: "#00CDAF"
#     yellow: "#ECCB8B"
#     blue: "#7AA1C4"
#     magenta: "#BB8BAF"
#     cyan: "#78C2D2"
#     white: "#abb2bf"
# 
#   # Bright colors
#   bright:
#     black: "#3B4252"
#     red: "#CC5A68"
#     green: "#00CDAF"
#     yellow: "#ECCB8B"
#     blue: "#7AA1C4"
#     magenta: "#BB8BAF"
#     cyan: "#78C2D2"
#     white: "#D7DEEA"

# Colors (One Darker)
# colors:
#   # Default colors
#   primary:
#     background: "#1E1E1E"
#     # background: "#2E3440"
#     foreground: "#D8DEE9"
# 
#   # Normal colors
#   normal:
#     black: "#3B4252"
#     red: "#D54646"
#     green: "#23D18B"
#     yellow: "#D7BA7D"
#     blue: "#569CD6"
#     magenta: "#C586C0"
#     cyan: "#29B8DB"
#     white: "#abb2bf"
# 
#   # Bright colors
#   bright:
#     black: "#3B4252"
#     red: "#D54646"
#     green: "#23D18B"
#     yellow: "#D7BA7D"
#     blue: "#569CD6"
#     magenta: "#C586C0"
#     cyan: "#29B8DB"
#     white: "#ECEFF4"

# Pale Night
#colors:
  ## Default colors
  #primary:
    #background: '0x292d3e'
    #foreground: '0xd0d0d0'

  ## Normal colors
  #normal:
    #black:   '0x292d3e'
    #red:     '0xf07178'
    #green:   '0xc3e88d'
    #yellow:  '0xffcb6b'
    #blue:    '0x82aaff'
    #magenta: '0xc792ea'
    #cyan:    '0x89ddff'
    #white:   '0xd0d0d0'

  ## Bright colors
  #bright:
    #black:   '0x434758'
    #red:     '0xff8b92'
    #green:   '0xddffa7'
    #yellow:  '0xffe585'
    #blue:    '0x9cc4ff'
    #magenta: '0xe1acff'
    #cyan:    '0xa3f7ff'
    #white:   '0xffffff'

# Colors (Dogrun)
# colors:
#   # Default colors
#   primary:
#     background: "#222433"
#     foreground: "#9ea3c0"
# 
#   # Normal colors
#   normal:
#     black: "#111219"
#     red: "#db5966"
#     green: "#7cbe8c"
#     yellow: "#9b956b"
#     blue: "#2994c6"
#     magenta: "#6c75cb"
#     cyan: "#73c1a9"
#     white: "#9ea3c0"
# 
#   # Bright colors
#   bright:
#     black: "#6A709C"
#     red: "#FD6776"
#     green: "#96E6A9"
#     yellow: "#DFD69A"
#     blue: "#35BFFF"
#     magenta: "#8893FF"
#     cyan: "#84DEC2"
#     white: "#D0D7FD"

# Colors (One Dark)
#colors:
  ## Default colors
  #primary:
    #background: '0x282c34'
    #foreground: '0xabb2bf'

  ## Normal colors
  #normal:
    #black:   '0x282c34'
    #red:     '0xe06c75'
    #green:   '0x98c379'
    #yellow:  '0xe5c07b'
    #blue:    '0x61afef'
    #magenta: '0xc678dd'
    #cyan:    '0x56b6c2'
    #white:   '0xabb2bf'

  ## Bright colors
  #bright:
    #black:   '0x3e4452'
    #red:     '0xbe5046'
    #green:   '0x98c379'
    #yellow:  '0xd19a66'
    #blue:    '0x61afef'
    #magenta: '0xc678dd'
    #cyan:    '0x56b6c2'
    #white:   '0x5c6370'

# Colors (Gruvbox Material)
colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd4be98'

  # Normal colors
  normal:
    black:   '0x32302f'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xd4be98'

  # Bright colors
  bright:
    black:   '0x32302f'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xd4be98'

# Colors (Tokyo Night)
#colors:
#  # Default colors
#  primary:
#    background: '0x1a1b26'
#    foreground: '0xa9b1d6'
#
#  # Normal colors
#  normal:
#    black:   '0x32344a'
#    red:     '0xf7768e'
#    green:   '0x9ece6a'
#    yellow:  '0xe0af68'
#    blue:    '0x7aa2f7'
#    magenta: '0xad8ee6'
#    cyan:    '0x449dab'
#    white:   '0x787c99'
#
#  # Bright colors
#  bright:
#    black:   '0x444b6a'
#    red:     '0xff7a93'
#    green:   '0xb9f27c'
#    yellow:  '0xff9e64'
#    blue:    '0x7da6ff'
#    magenta: '0xbb9af7'
#    cyan:    '0x0db9d7'
#    white:   '0xacb0d0'

# Colors (Aubergine)
#colors:
  ## Default colors
  #primary:
    #background: "#1A222E"
    #foreground: "#CBC7C0"

  ## Normal colors
  #normal:
    #black: "#000000"
    #red: "#F67E7F"
    #green: "#7ECABB"
    #yellow: "#FFD376"
    #blue: "#56B5D1"
    #magenta: "#B67ED0"
    #cyan: "#59E0DF"
    #white: "#E5E5E5"

  ## Bright colors
  #bright:
    #black: "#666666"
    #red: "#F67E7F"
    #green: "#7ECABB"
    #yellow: "#FFD376"
    #blue: "#56B5D1"
    #magenta: "#B67ED0"
    #cyan: "#59E0DF"
    #white: "#E5E5E5"

  #cursor:
    #style: Block
    #unfocused_hollow: true
    #text: CellBackground
    #cursor: CellForeground

  #vi_mode_cursor:
    #text: CellBackground
    #cursor: CellForeground

  #selection:
    #text: "0xffffff"
    #background: "0xdc3232"
    #white: "0xffffff"

  #search:
    #matches:
      #foreground: "#000000"
      #background: "#ffffff"

    #bar:
      #background: "#c5c8c6"
      #foreground: "#1d1f21"

# Colors (Dracula PRO)
#colors:
  ## Default colors
  #primary:
    #background: '0x22212c'
    #foreground: '0xf8f8f2'


  ## Cursor colors
  #cursor:
    #text: '0x454158'
    #cursor: '0xf8f8f2'

  ## Selection colors
  #selection:
    #text: '0xf8f8f2'
    #background: '0x454158'

  ## Normal colors
  #normal:
    #black:   '0x22212c'
    #red:     '0xff9580'
    #green:   '0x8aff80'
    #yellow:  '0xffff80'
    #blue:    '0x9580ff'
    #magenta: '0xff80bf'
    #cyan:    '0x80ffea'
    #white:   '0xf8f8f2'

  # Bright colors
  #bright:
    #black:   '0x7C6EAD'
    #red:     '0xffaa99'
    #green:   '0xa2ff99'
    #yellow:  '0xffff99'
    #blue:    '0xaa99ff'
    #magenta: '0xff99cc'
    #cyan:    '0x99ffee'
    #white:   '0xffffff'

# Mouse
mouse:
  hide_when_typing: true

# Key bindings
key_bindings:
  - { key: N,       mods: Control|Shift,    action: SpawnNewInstance }
  - { key: Right,   mods: Alt,              chars: "\x1bf" }
  - { key: Left,    mods: Alt,              chars: "\x1bb" }
  - { key: Right,   mods: Command,          chars: "\x1bOF" }
  - { key: Left,    mods: Command,          chars: "\x1bOH" }
  - { key: Back,    mods: Command,          chars: "\x15" }
