# Window Customisation
window:
  dimensions:
    columns: 95
    lines: 30
  position:
    x: 310
    y: 500
  padding:
    x: 30
    y: 30
  decorations: buttonless

scrolling:
  history: 10000
  multiplier: 3

background_opacity: 1

# Font configuration
font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic
  size: 14.0

  offset:
    x: 0
    y: 2

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

## Colors (Dogrun)
#colors:
  ## Default colors
  #primary:
    #background: "#222433"
    #foreground: "#9ea3c0"

  ## Normal colors
  #normal:
    #black: "#111219"
    #red: "#db5966"
    #green: "#7cbe8c"
    #yellow: "#9b956b"
    #blue: "#2994c6"
    #magenta: "#6c75cb"
    #cyan: "#73c1a9"
    #white: "#9ea3c0"

  ## Bright colors
  #bright:
    #black: "#6A709C"
    #red: "#FD6776"
    #green: "#96E6A9"
    #yellow: "#DFD69A"
    #blue: "#35BFFF"
    #magenta: "#8893FF"
    #cyan: "#84DEC2"
    #white: "#D0D7FD"

# Colors (Aubergine)
colors:
  # Default colors
  primary:
    background: "#1A222E"
    foreground: "#CBC7C0"

  # Normal colors
  normal:
    black: "#000000"
    red: "#F67E7F"
    green: "#7ECABB"
    yellow: "#FFD376"
    blue: "#56B5D1"
    magenta: "#B67ED0"
    cyan: "#59E0DF"
    white: "#E5E5E5"

  # Bright colors
  bright:
    black: "#666666"
    red: "#F67E7F"
    green: "#7ECABB"
    yellow: "#FFD376"
    blue: "#56B5D1"
    magenta: "#B67ED0"
    cyan: "#59E0DF"
    white: "#E5E5E5"

  cursor:
    style: Block
    unfocused_hollow: true
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: "0xffffff"
    background: "0xdc3232"
    white: "0xffffff"

  search:
    matches:
      foreground: "#000000"
      background: "#ffffff"

    bar:
      background: "#c5c8c6"
      foreground: "#1d1f21"

# Key bindings
key_bindings:
  - { key: N,       mods: Control|Shift,    action: SpawnNewInstance }
  - { key: Right,   mods: Alt,              chars: "\x1bf" }  
  - { key: Left,    mods: Alt,              chars: "\x1bb" }  
  - { key: Right,   mods: Command,          chars: "\x1bOF" }  
  - { key: Left,    mods: Command,          chars: "\x1bOH" }  
  - { key: Back,    mods: Command,          chars: "\x15" }  
