[window]
dimensions = { columns = 85, lines = 25 }
position = { x = 310, y = 500 }
padding = { x = 30, y = 30 }
decorations = "buttonless"

[scrolling]
history = 10000
multiplier = 3

background_opacity = 1.0

[font]
normal = { family = "FiraCode Nerd Font", style = "Light" }
bold = { family = "FiraCode Nerd Font", style = "Medium" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 14.0
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 0 }

draw_bold_text_with_bright_colors = true

[colors]
[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[colors.normal]
black = "0x32344a"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xad8ee6"
cyan = "0x449dab"
white = "0x787c99"

[colors.bright]
black = "0x444b6a"
red = "0xff7a93"
green = "0xb9f27c"
yellow = "0xff9e64"
blue = "0x7da6ff"
magenta = "0xbb9af7"
cyan = "0x0db9d7"
white = "0xacb0d0"

[mouse]
hide_when_typing = true