command_timeout = 1000
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = "bold blue"
format = '[ $user@]($style)'

[hostname]
style = "bold blue"
format = '[$hostname]($style) '

[git_branch]
symbol = " "

[git_status]
ahead = "󱦲"
behind = "󱦳"
